# Settings for Touch Training Phases 3 - 5 and Tasks.

LOG_FILENAME_PREFIX='log'
RFID_READ_TIMEOUT=5

N_TRIALS=10
TRIAL_DELAY=1
REWARD_MODE='Automatic'
REWARD_DELAY=1
REWARD_VOLUME=300
REWARD_VOL_FACTOR=0.001 / 3
BUZZER_LED_TIME=0.5
BUZZER_PITCH_CORRECT=800
BUZZER_PITCH_INCORRECT=100

PIN_PUMP=13
PIN_BEAM=8
PIN_BUZZER=10
PIN_LED_BLUE=16
PIN_LED_GREEN=18

